import "./information.css";
import React from "react";
import siegeImage from "../../asset/image/siege.png";

export default function Information() {
  document.title = "SafeNet - Information";

  return (
    <div className="information">
      <div className="information-container">
        <h1 styles="font-size: 400%;">Informations générales</h1>
        <h3>Dans cette section, vous retrouverez des informations et liens pour consolider vos connaissances.</h3><br></br>
        <p>Dans un contexte où le progrès technologique avance à une vitesse effrénée et dans lequel les attaques informatiques sont de plus en plus fréquentes, la cybersécurité occupe une place de plus en plus importante. Nous sommes tous vulnérables : États, grands groupes, petites et moyennes entreprises, organismes, particuliers… Bien se protéger sur le web est  devenu une véritable préoccupation pour préserver ses actifs informatiques, qu’ils soient matériels ou immatériels. Une multitude d’attaques peuvent être menées par des pirates informatiques pour infecter votre système. Faisons un petit tour d'horizon non exhaustif de ces attaques.</p><br></br>
        <h1 styles="text-align: left;">Le cryptojacking, minage de cryptomonnaie malveillant</h1><br></br>
        <p>L’arrivée des cryptomonnaies et l’engouement autour du Bitcoin ont engendré de nouvelles menaces comme le cryptojacking, également appelé minage de cryptomonnaie malveillant. Les hackers introduisent des logiciels pour corrompre les systèmes et ressources d’une machine (PC, smartphone, serveur…), afin d’exploiter la cryptomonnaie en arrière plan et engendrer du profit de façon cachée.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les ransomwares, rançongiciels</h1><br></br>
        <p>D’autres hackers vont plus loin, avec des ransomwares. C’est un type d’attaque de plus en plus fréquent : une personne pirate un ordinateur ou un serveur et demande une rançon, en bitcoin, à l’utilisateur ou l’administrateur. Pendant ce temps, les données sont bloquées : le hacker vous contraint de payer pour récupérer vos données.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les intrusions sur les objets connectés</h1><br></br>
        <p>De plus en plus de personnes se procurent des objets connectés : montres, assistants vocaux, dispositifs d’éclairage ou de sécurité… Il y en a une multitude pour des usages de plus en plus répandus dans la vie quotidienne, et ce à domicile comme dans les entreprises. Mais quel est leur degré de vulnérabilité et quels sont les risques encourus par les possesseurs de ces objets ? Les sociétés qui commercialisent ces solutions doivent redoubler d’efforts pour mettre en place des pare-feux et implémenter des programmes de mises à jour récurrentes lors de leur conception, afin de les protéger d’éventuelles attaques et empêcher que des failles soient exploitées par des personnes mal intentionnées.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les attaques géopolitiques</h1><br></br>
        <p>Certains pays sont connus pour leurs attaques informatiques, menées par des organismes gouvernementaux ou des activistes locaux. Ces hacks peuvent être réalisés contre un autre pays pour le déstabiliser, l’intimider, mais également voler certaines technologies dans le cadre de l’espionnage industriel. Dans ce cas précis il est important pour les entreprises technologiques de prendre des précautions, notamment dans la mise en place de normes de sécurité, le choix du lieu où elles hébergent leurs données et leurs prestataires.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les scripts intersites ou cross-site scripting (XSS)</h1><br></br>
        <p>Les hackers qui ont recours à cette pratique lancent des attaques XSS en injectant du contenu dans une page, ce qui corrompt le navigateur de la cible. Un pirate peut ainsi modifier la page web selon ses envies, voler des informations sur des cookies, lui permettant de détourner des sites à volonté afin de récupérer des données sensibles, ou d’injecter un code malveillant qui sera par la suite exécuté.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les malwares sur mobile</h1><br></br>
        <p>Nous passons désormais plus de temps sur mobile que devant la TV, les hackers l’ont bien compris et n’ont pas tardé à exploiter cette opportunité. En 2018, 116,5 millions d’attaques sur mobile se sont produites selon Kaspersky, soit quasiment 2 fois plus qu’en 2017 (66,4 millions). Certains fabricants commercialisent des terminaux vulnérables qui sont les cibles privilégiées des pirates et de leurs malwares, qui ont eux gagné en efficacité et en précision. De nombreuses solutions de gestion des appareils mobiles sont disponibles sur le marché, et peuvent être utilisées par les entreprises pour protéger leurs salariés et les données stratégiques.</p><br></br><br></br>
        <h1 styles="text-align: left;">Le phishing</h1><br></br>
        <p>La fameuse fenêtre pop-up qui s’affiche et vous propose de cliquer pour récupérer le million d’euros que vous avez gagné par tirage au sort, le faux mail que vous recevez de votre banque vous demandant de saisir vos identifiants… Nous avons tous déjà été confronté au phishing au moins une fois en surfant sur le net. Dès que l’on clique sur un lien de ce type, on expose ses données personnelles. Les pirates peuvent voler des numéros de carte de crédit ou des informations financières, ainsi que des identifiants de connexion ou des données confidentielles en reproduisant des interfaces de saisie.</p><br></br><br></br>
        <h1 styles="text-align: left;">Le spoofing</h1><br></br>
        <p>Vous avez reçu un email d’un proche (voire un email de vous-même) un peu bizarre ? Ne versez pas 520 euros en bitcoin sur un compte inconnu sans réfléchir : vous êtes sûrement victime de spoofing. Il s’agit d’une méthode consistant à usurper l’adresse email d’envoi. Ce type d’attaque est très fréquent (et parfois crédible). Généralement, le pirate tente de vous faire croire des choses qui sont en réalité totalement fausses : il détient des informations sur vous, un proche a besoin de vous etc.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les attaques cyber-physiques</h1><br></br>
        <p>Les attaques de ce type ne sont pas uniquement à l’affiche des James Bond ou d’autres films d’action. Le piratage de systèmes de transport, d’usines, de réseaux électriques ou d’installations de traitement de l’eau arrive réellement, pour neutraliser un site spécifique ou réaliser tout autre projet hostile via la propagation d’un virus informatique. La protection de systèmes sensibles repose sur un ensemble de pratiques dont la segmentation du réseau par exemple. Des technologies de pointe de détection et prévention d’intrusion sont développées sur mesure pour ces systèmes, en tenant compte des différentes particularités d’usages et protocoles de sécurité.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les attaques contre les appareils et dossiers médicaux électroniques</h1><br></br>
        <p>Le milieu médical est lui aussi friand des nouvelles technologies et des nouveaux appareils mis à sa disposition. De nombreuses données sensibles et confidentielles sont hébergées, ce qui là encore augmente l’intérêt des pirates et par conséquent la vulnérabilité du secteur aux cyberattaques. Quand les hackers s’introduisent dans les systèmes d’hôpitaux et arrivent à voir accès à ces informations, le préjudice en termes de vie privée est considérable. Les conséquences que pourraient avoir une intrusion et le piratage d’appareils médicaux seraient quant à elles dramatiques.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les attaques contre les véhicules connectés et semi-autonomes</h1><br></br>
        <p>Tous les constructeurs se lancent dans la course aux voitures et autres véhicules autonomes, chacun essayant de faire mieux que les concurrents en proposant des technologies plus avancées. Ces véhicules possèdent des capteurs qui font appel à des programmes informatiques. Certaines fonctionnalités peuvent même être contrôlées via un smartphone, ce qui les rend d’autant plus vulnérables aux attaques orchestrées par des pirates. En plus d’accéder là encore à des données sensibles, les hackers pourrait accéder aux systèmes du véhicule et causer des pannes, voire des accidents.</p><br></br><br></br>
        <h1 styles="text-align: left;">Les attaques contre les espaces de stockage cloud</h1><br></br>
        <p>Beaucoup de particuliers et d’entreprises ont abandonné le stockage traditionnel au profit du cloud computing, accessible partout. Les pirates informatiques peuvent cependant utiliser des mécanismes pour voler des clés de chiffrement et ainsi accéder à des informations sensibles et autres données confidentielles. Pour contrer ce fléau, il est conseillé d’investir dans un système de chiffrement sécurisé et un certificat SSL, fournis par un prestataire de confiance afin de protéger les données de votre société.</p><br></br><br></br>
        <a href="https://www.blogdumoderateur.com/cybersecurite-types-attaques-informatiques/">Source des informations</a><br></br>
        <img src={siegeImage} className="information-siege" alt="Siege Social" />
      </div>
    </div>
  );
}
